// ============================================================
// Service Worker - Rainfall Monitoring PWA
// Generated by @rochmadjeka PWA Wrapper
// ============================================================

const CACHE_NAME = 'rainfall-pwa-v1';
const STATIC_ASSETS = [
  './',
  './index.html',
  './manifest.json',
  './icons/icon-192.png',
  './icons/icon-512.png'
];

// ---- INSTALL: Cache static assets ----
self.addEventListener('install', event => {
  event.waitUntil(
    caches.open(CACHE_NAME).then(cache => {
      return cache.addAll(STATIC_ASSETS);
    }).then(() => self.skipWaiting())
  );
});

// ---- ACTIVATE: Hapus cache lama ----
self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys().then(keys =>
      Promise.all(
        keys.filter(key => key !== CACHE_NAME).map(key => caches.delete(key))
      )
    ).then(() => self.clients.claim())
  );
});

// ---- FETCH: Strategi Cache-First untuk aset lokal ----
// Untuk request ke Google Apps Script (iframe), langsung ke network
self.addEventListener('fetch', event => {
  const url = new URL(event.request.url);

  // Bypass service worker untuk semua request ke script.google.com
  // (iframe GAS harus selalu ke network)
  if (url.hostname.includes('google.com') ||
      url.hostname.includes('googleapis.com') ||
      url.hostname.includes('gstatic.com')) {
    return; // Biarkan browser handle langsung
  }

  // Cache-first untuk aset lokal (shell PWA)
  event.respondWith(
    caches.match(event.request).then(cached => {
      return cached || fetch(event.request).then(response => {
        // Simpan respons baru ke cache
        if (response && response.status === 200 && response.type === 'basic') {
          const clone = response.clone();
          caches.open(CACHE_NAME).then(cache => cache.put(event.request, clone));
        }
        return response;
      });
    }).catch(() => {
      // Fallback ke index.html saat offline
      if (event.request.destination === 'document') {
        return caches.match('./index.html');
      }
    })
  );
});

// ---- MESSAGE: Trigger update manual ----
self.addEventListener('message', event => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
